[input]
prepend_keymap = [
  { on = "<Esc>", run = "close", desc = "Cancel input" }
]

[manager]
prepend_keymap = [
  { on = "<Esc>", run = "close", desc = "Close yazi" },
  { on = "<Enter>", run = "plugin --sync smart-enter", desc = "Enter directory, or open file" },
  { on = "o", run = "shell \"$SHELL\" --block --confirm ", desc = "Open shell" },
]
